// <auto-generated />
using System;
using ApiMorph.Orchestrator.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiMorph.Orchestrator.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApiMorphDbContext))]
    partial class ApiMorphDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ApiMorph.Orchestrator.Domain.Entities.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Evidence")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Line")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScanJobId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScanJobId");

                    b.ToTable("Findings");
                });

            modelBuilder.Entity("ApiMorph.Orchestrator.Domain.Entities.Installation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Installations");
                });

            modelBuilder.Entity("ApiMorph.Orchestrator.Domain.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubOwner")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubRepo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId");

                    b.HasIndex("GitHubOwner", "GitHubRepo")
                        .IsUnique();

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("ApiMorph.Orchestrator.Domain.Entities.ScanJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("ScanJobs");
                });

            modelBuilder.Entity("ApiMorph.Orchestrator.Domain.Entities.Finding", b =>
                {
                    b.HasOne("ApiMorph.Orchestrator.Domain.Entities.ScanJob", "ScanJob")
                        .WithMany("Findings")
                        .HasForeignKey("ScanJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanJob");
                });

            modelBuilder.Entity("ApiMorph.Orchestrator.Domain.Entities.Repository", b =>
                {
                    b.HasOne("ApiMorph.Orchestrator.Domain.Entities.Installation", "Installation")
                        .WithMany("Repositories")
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Installation");
                });

            modelBuilder.Entity("ApiMorph.Orchestrator.Domain.Entities.ScanJob", b =>
                {
                    b.HasOne("ApiMorph.Orchestrator.Domain.Entities.Repository", "Repository")
                        .WithMany("ScanJobs")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("ApiMorph.Orchestrator.Domain.Entities.Installation", b =>
                {
                    b.Navigation("Repositories");
                });

            modelBuilder.Entity("ApiMorph.Orchestrator.Domain.Entities.Repository", b =>
                {
                    b.Navigation("ScanJobs");
                });

            modelBuilder.Entity("ApiMorph.Orchestrator.Domain.Entities.ScanJob", b =>
                {
                    b.Navigation("Findings");
                });
#pragma warning restore 612, 618
        }
    }
}
