namespace ApiMorph.Cli.Commands;

internal static class InitCommand
{
    public static int Run(string[] args)
    {
        var repositoryRoot = CliPaths.FindRepositoryRoot();
        var deployDir = CliPaths.GetDeployDirectory(repositoryRoot);
        var envPath = CliPaths.GetEnvFilePath(repositoryRoot);
        var examplePath = CliPaths.GetEnvExamplePath(repositoryRoot);
        var secretsDir = Path.Combine(deployDir, "secrets");

        if (!Directory.Exists(deployDir))
        {
            Console.Error.WriteLine($"Deploy directory not found: {deployDir}");
            return 1;
        }

        Console.WriteLine("ApiMorph init");
        Console.WriteLine("=============");
        Console.WriteLine($"Repository: {repositoryRoot}");
        Console.WriteLine();
        Console.WriteLine("Secrets for self-hosted use go in deploy/.env and deploy/secrets/.");
        Console.WriteLine("You do not need `dotnet user-secrets` (that is optional for local SDK developers only).");
        Console.WriteLine();

        if (File.Exists(envPath))
        {
            Console.Write($"Overwrite existing {envPath}? [y/N]: ");
            var answer = Console.ReadLine()?.Trim().ToLowerInvariant();
            if (answer is not "y" and not "yes")
            {
                Console.WriteLine("Cancelled.");
                return 0;
            }
        }

        var useApp = PromptYesNo("Configure GitHub App auth? (recommended; otherwise PAT fallback)", defaultYes: true);

        string? appId = null;
        string? installationId = null;
        string? webhookSecret = null;
        string appPrivateKeyPath = string.Empty;
        string githubToken = string.Empty;

        if (useApp)
        {
            appId = PromptValue("GitHub App ID", "");
            installationId = PromptValue("GitHub App installation ID", "");
            webhookSecret = PromptSecret("Webhook secret (optional, Stage 8)");
            Directory.CreateDirectory(secretsDir);
            Console.WriteLine();
            Console.WriteLine($"Place your App private key PEM at: {Path.Combine(secretsDir, "github-app.pem")}");
            Console.WriteLine("Then uncomment the secrets volume in deploy/docker-compose.yml");
            Console.WriteLine("and set GitHub__AppPrivateKeyPath=/run/secrets/github-app.pem");
            appPrivateKeyPath = "/run/secrets/github-app.pem";
        }

        githubToken = PromptSecret(useApp
            ? "Optional PAT fallback (blank to skip)"
            : "GitHub PAT (contents + pull_requests)");

        var patchEnabled = PromptYesNo("Enable deterministic patches?", defaultYes: true);
        var llmEnabled = PromptYesNo("Enable LLM-assisted patches?", defaultYes: false);
        var llmProvider = "ollama";
        var llmModel = "qwen2.5";
        var ollamaUrl = "http://host.docker.internal:11434";

        if (llmEnabled)
        {
            llmProvider = PromptValue("LLM provider", "ollama");
            llmModel = PromptValue("LLM model", "qwen2.5");
            ollamaUrl = PromptValue("Ollama base URL", ollamaUrl);
        }

        var lines = new List<string>
        {
            "# Generated by apimorph init",
            "# Self-hosted secrets: use this .env + deploy/secrets/*.pem (gitignored).",
            "# Do not use `dotnet user-secrets` unless you are a local SDK developer.",
            $"GitHub__AppId={appId ?? string.Empty}",
            $"GitHub__InstallationId={installationId ?? string.Empty}",
            $"GitHub__AppPrivateKeyPath={appPrivateKeyPath}",
            $"GitHub__WebhookSecret={webhookSecret ?? string.Empty}",
            $"GitHub__Token={githubToken}",
            "GitHub__CommitAuthorName=ApiMorph Bot",
            "GitHub__CommitAuthorEmail=apimorph-bot@users.noreply.github.com",
            $"Patch__Enabled={(patchEnabled ? "true" : "false")}",
            $"Llm__Enabled={(llmEnabled ? "true" : "false")}",
            $"LLM__PROVIDER={llmProvider}",
            $"LLM__MODEL={llmModel}",
            $"OLLAMA_BASE_URL={ollamaUrl}",
            "AUTO_MERGE=false",
            string.Empty,
        };

        File.WriteAllLines(envPath, lines);
        Console.WriteLine();
        Console.WriteLine($"Wrote {envPath}");

        if (File.Exists(examplePath))
        {
            Console.WriteLine($"Reference: {examplePath}");
        }

        Console.WriteLine();
        Console.WriteLine("Next steps:");
        if (useApp)
        {
            Console.WriteLine($"  1. Copy App private key to {Path.Combine(secretsDir, "github-app.pem")}");
            Console.WriteLine("  2. Uncomment the github-app.pem volume in deploy/docker-compose.yml");
        }

        Console.WriteLine($"  cd {deployDir}");
        Console.WriteLine("  docker compose up --build -d");
        Console.WriteLine("  apimorph doctor");
        Console.WriteLine("  apimorph scan --owner YOUR_ORG --repo YOUR_REPO --pr");

        return 0;
    }

    private static string PromptValue(string label, string defaultValue)
    {
        Console.Write(string.IsNullOrEmpty(defaultValue) ? $"{label}: " : $"{label} [{defaultValue}]: ");
        var value = Console.ReadLine()?.Trim();
        return string.IsNullOrWhiteSpace(value) ? defaultValue : value;
    }

    private static bool PromptYesNo(string label, bool defaultYes)
    {
        var hint = defaultYes ? "Y/n" : "y/N";
        Console.Write($"{label} [{hint}]: ");
        var value = Console.ReadLine()?.Trim().ToLowerInvariant();
        return value switch
        {
            "" => defaultYes,
            "y" or "yes" => true,
            "n" or "no" => false,
            _ => defaultYes,
        };
    }

    private static string PromptSecret(string label)
    {
        Console.Write($"{label}: ");
        return Console.ReadLine()?.Trim() ?? string.Empty;
    }
}
