namespace ApiMorph.Cli.Commands;

internal static class ReposCommand
{
    public static int Run(string[] args)
    {
        if (args.Length == 0 || args[0] is "--help" or "-h")
        {
            PrintHelp();
            return 0;
        }

        return args[0].ToLowerInvariant() switch
        {
            "add" => Add(args.Skip(1).ToArray()),
            "list" => List(),
            _ => Unknown(args[0]),
        };
    }

    private static int Add(string[] args)
    {
        string? owner = null;
        string? name = null;
        var providers = "stripe";
        var branch = "main";

        for (var i = 0; i < args.Length; i++)
        {
            switch (args[i])
            {
                case "--owner" or "-o":
                    owner = Read(args, ref i);
                    break;
                case "--repo" or "-r":
                    name = Read(args, ref i);
                    break;
                case "--providers":
                    providers = Read(args, ref i) ?? providers;
                    break;
                case "--branch":
                    branch = Read(args, ref i) ?? branch;
                    break;
            }
        }

        if (string.IsNullOrWhiteSpace(owner) || string.IsNullOrWhiteSpace(name))
        {
            Console.Error.WriteLine("Required: --owner and --repo");
            PrintHelp();
            return 1;
        }

        var root = CliPaths.FindRepositoryRoot();
        var reposDir = Path.Combine(root, "deploy", "config", "repos.d");
        Directory.CreateDirectory(reposDir);
        var fileName = $"{owner}-{name}.conf".ToLowerInvariant();
        var path = Path.Combine(reposDir, fileName);

        var content = $"""
            # Generated by apimorph repos add
            repo.owner = {owner}
            repo.name = {name}
            repo.enabled = true
            repo.providers = {providers}
            repo.default_branch = {branch}
            repo.create_pull_request = true
            # repo.webhook_branches = main
            # repo.schedule_cron = 0 3 * * *
            """;

        File.WriteAllText(path, content + Environment.NewLine);
        Console.WriteLine($"Wrote {path}");
        Console.WriteLine("Restart orchestrator (or wait for next sync) to load the repo.");
        return 0;
    }

    private static int List()
    {
        var root = CliPaths.FindRepositoryRoot();
        var reposDir = Path.Combine(root, "deploy", "config", "repos.d");
        if (!Directory.Exists(reposDir))
        {
            Console.WriteLine("No repos.d directory.");
            return 0;
        }

        foreach (var file in Directory.GetFiles(reposDir, "*.conf")
                     .Where(f => !f.EndsWith(".example", StringComparison.OrdinalIgnoreCase))
                     .OrderBy(f => f))
        {
            Console.WriteLine(Path.GetFileName(file));
        }

        return 0;
    }

    private static string? Read(string[] args, ref int index)
    {
        if (index + 1 >= args.Length)
        {
            return null;
        }

        index++;
        return args[index];
    }

    private static int Unknown(string command)
    {
        Console.Error.WriteLine($"Unknown repos command: {command}");
        PrintHelp();
        return 1;
    }

    private static void PrintHelp()
    {
        Console.WriteLine("""
            apimorph repos — manage registered repository conf files

            Usage:
              apimorph repos add --owner ORG --repo NAME [--providers stripe] [--branch main]
              apimorph repos list
            """);
    }
}
